function counter(val, step) {
  let arr = [val];
  for (let i = 0; i < 1000; i += step)
    arr.push(val += step);
  for (j = 0; j <= 1000; j++) {
    if (arr[j] >= 1000) {
      do {
        arr.pop();
      } while (arr[j] > 1000)
      return arr;
    }
  }
}
function numGen(max,min) {
//time is the number generated by getMilliseconds()
  const time = new Date().getMilliseconds();
  //num is the power of time e.g 10^2
 const pow=time.toString().length;
 const num1=Math.pow(10,pow);
 //result is a random number between max and min
 const num2=time/num1;
 const result=Math.floor((num2)*(max-min+1))+min
  return result;
}
console.log(counter(1, 30));
console.log(numGen(2,10));
//jsfiddle link (https://jsfiddle.net/S3milore/8k1stLoj/216/)
